# Generated by Django 3.0.8 on 2020-08-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200821_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yeahhhhh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aaa', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='testimage',
            name='image',
            field=models.TextField(),
        ),
    ]
