# Generated by Django 3.0.8 on 2020-08-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20200823_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimage',
            name='created_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimage',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='yeahhhhh',
            name='aaa',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
