# Generated by Django 3.0.8 on 2020-08-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_testimage_word'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Words',
        ),
    ]
