# Generated by Django 3.0.8 on 2020-08-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20200828_1419'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Words',
        ),
    ]
