# Generated by Django 3.0.8 on 2020-08-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_delete_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(blank=True, max_length=50)),
                ('meaning', models.CharField(blank=True, max_length=100)),
                ('final_images', models.ImageField(blank=True, upload_to='new_images/')),
            ],
        ),
    ]
