# Generated by Django 3.0.8 on 2020-09-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=15)),
                ('user_age', models.CharField(choices=[('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('24~', '24~')], default='18', max_length=3)),
                ('user_sex', models.CharField(choices=[('M', '男'), ('F', '女'), ('E', 'その他')], default='M', max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Yeahhhhh',
        ),
    ]
