# Generated by Django 3.0.8 on 2020-09-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_auto_20200905_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_data',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
