# Generated by Django 3.0.8 on 2020-09-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_auto_20200905_1257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestImage',
        ),
    ]
