# Generated by Django 3.0.8 on 2020-09-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_testimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='final_data',
            name='user',
        ),
        migrations.DeleteModel(
            name='TestImage',
        ),
        migrations.DeleteModel(
            name='Final_data',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
