# Generated by Django 3.0.8 on 2020-09-07 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_final_data_testimage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karuta_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mistake_count', models.IntegerField(default=0)),
                ('finished_time', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.User')),
            ],
        ),
    ]
